In [4]:
##Create a custom dtype that describes a color as four unsigned bytes (RGBA)
import numpy as np
rgba_dtype=np.dtype([("red",np.uint8),("green",np.uint8),("blue",np.uint8),("alpha",np.uint8)])
color=np.array([(255,0,0,255), (0,255,0,255),(0,0,255,255),(255,255,0,128)],dtype=rgba_dtype)
print(color)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255,   0, 128)]


In [11]:
##Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
import numpy as np
mat1=np.ones((5,3),dtype=np.int32)
mat2=np.zeros((3,2),dtype=np.int32)
print(np.dot(mat1,mat2))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [12]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [14]:
##What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_2951/3987877459.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_2951/3987877459.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_2951/3987877459.py:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [5]:
## Given a 1D array, negate all elements which are between 3 and 8, in place
import numpy as np
arr=np.arange(11)
print(arr)
arr[(arr>3) & (arr<8)]*=-1
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [6]:
##How to round away from zero a float array
import numpy as np
z=np.random.rand(10)
result=np.ceil(np.abs(z)*np.sign(z))
print(result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
