In [ ]:
##How to find common values between two arrays
import numpy as np
arr1=[1,2,3,4,5]
arr2=[4,5,6,7,8]
common_values=np.intersect1d(arr1,arr2)
print(common_values)

[4 5]


In [ ]:
##Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_3019/2038447907.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [ ]:
###How to get the dates of yesterday, today and tomorrow
import numpy as np
today=np.datetime64('today','D')
yesterday=today-np.timedelta64('1','D')
tommorrow=today+np.timedelta64('1','D')
print(yesterday,today,tommorrow)

2026-05-19 2026-05-20 2026-05-21


In [ ]:
##How to get all the dates corresponding to the month of July 2016
import numpy as np
july_2016=np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
##How to compute ((A+B)*(-A/2)) in place (without copy)
import numpy as np
A=np.ones(4)*3
B=np.ones(4)*2
np.add(A,B,out=B)
np.divide(A,-2,out=A)
np.multiply(B,A,out=A)
print(A)

[-7.5 -7.5 -7.5 -7.5]


In [3]:
## Extract the integer part of a random array of positive numbers using 4 different methods
import numpy as np
z=np.random.uniform(0,10,10)
print(z.astype(int))
print(np.trunc(z))
print(z//1)
print(np.floor(z))


[1 9 9 1 0 2 8 2 9 5]
[1. 9. 9. 1. 0. 2. 8. 2. 9. 5.]
[1. 9. 9. 1. 0. 2. 8. 2. 9. 5.]
[1. 9. 9. 1. 0. 2. 8. 2. 9. 5.]


In [5]:
## Create a 5x5 matrix with row values ranging from 0 to 4
import numpy as np
mat=np.array([0,1,2,3,4] , dtype=int)
mat=np.tile(mat,(5,1))
print(mat)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [7]:
##Consider a generator function that generates 10 integers and use it to build an array
import numpy as np
def genrate():
  for i in range(10):
    yield i
arr=np.fromiter(genrate(),dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
##Create a vector of size 10 with values ranging from 0 to 1, both excluded
import numpy as np
arr1=np.linspace(0,1,12)[1:-1]
print(arr1)
arr2=np.arange(1,11)/11
print(arr2)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
